experiment:
  # 论文 Multi Phase 主实验：
  # Watercolor [1:3] -> Comic [4:6] -> Clipart [7:13] -> VOC [14:20]
  name: status2_multiphase_duet_yolo11n
  output_dir: outputs/status2_multiphase_duet_yolo11n
  seed: 42

detector:
  #base_weights: yolo11n.pt
  base_weights: /root/autodl-tmp/dual/dual_incremental_detection_master/status2/yolo11n.pt
  model_yaml: yolo11n.yaml
  total_classes: 20
  # 全局 20 类顺序。class_indices 使用这里的 0-based 下标。
  names:
    0: bicycle
    1: bird
    2: car
    3: cat
    4: dog
    5: person
    6: aeroplane
    7: boat
    8: bottle
    9: bus
    10: chair
    11: cow
    12: diningtable
    13: horse
    14: motorbike
    15: pottedplant
    16: sheep
    17: sofa
    18: train
    19: tvmonitor

training:
  # 论文补充材料：100 epochs、5 warmup、batch 64、AdamW。
  epochs: 100
  warmup_epochs: 5
  imgsz: 640
  batch: 64
  workers: 0
  device: 0
  optimizer: AdamW
  cos_lr: true
  lr0: 0.01
  lrf: 0.01
  freeze: 0
  weight_decay_first: 0.0005
  weight_decay_incremental: 0.001

duet:
  enabled: true
  use_duet_module: true
  gamma: 0.1
  alpha_base: 0.5
  distill_weight: 0.01
  dc_weight: 0.01
  distill_temperature: 2.0
  shared_key_exclude:
    - 23.dfl
    - 23.cv2
    - 23.cv3
  verbose_merge: false

tasks:
  # T1：Watercolor [1:3]
  # TODO：把 data 改成你服务器上 Watercolor 1-3 切片的真实 data.yaml。
  - name: watercolor_1_3
    data: /root/autodl-tmp/test_tasks_2/task_5/data.yaml
    class_indices: [0, 1, 2]
    labels_are_global: local    #将auto 改为local

  # T2：Comic [4:6]
  # TODO：把 data 改成你服务器上 Comic 4-6 切片的真实 data.yaml。
  - name: comic_4_6
    data: /root/autodl-tmp/test_tasks_2/task_8/data.yaml
    class_indices: [3, 4, 5]
    labels_are_global: local      #将auto 改为local

  # T3：Clipart [7:13]
  # TODO：把 data 改成你服务器上 Clipart 7-13 切片的真实 data.yaml。
  - name: clipart_7_13
    data: /root/autodl-tmp/test_tasks_2/task_4/data.yaml
    class_indices: [6, 7, 8, 9, 10, 11, 12]
    labels_are_global: local    #将auto 改为local

  # T4：VOC [14:20]
  # TODO：把 data 改成你服务器上 VOC 14-20 切片的真实 data.yaml。
  - name: voc_14_20
    data: /root/autodl-tmp/test_tasks_2/task_2/data.yaml
    class_indices: [13, 14, 15, 16, 17, 18, 19]
    labels_are_global: local     #将auto 改为local
